version: "3.8"
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    user: postgres
    environment:
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      timeout: 30s
      interval: 1s
      retries: 10
    command: ["postgres", "-c", "log_statement=all"]
